### ISSUE TITLE
提示 User does not exist

### ISSUE THREAD

**Issue by zhmushan** [wuhan2020/volunteer-certificate#110]
![image](https://user-images.githubusercontent.com/24505451/76861386-7d508200-6897-11ea-89d0-6ab1339555d5.png)
![image](https://user-images.githubusercontent.com/24505451/76861408-89d4da80-6897-11ea-8f4c-39b5eda074e5.png)

**Comment by zhaofeng-shu33** [comment]
which user?

**Comment by zhmushan** [comment]
zhbnh9988@gmail.com

**Comment by youqingxiaozhua** [comment]
Please check if there is a new mail message, the link has changed, please refer to the new one

**Comment by zhmushan** [comment]
> Please check if there is a new mail message, the link has changed, please refer to the new one

Sadly i have only received this email

**Comment by youqingxiaozhua** [comment]
It may be labeled as spam, so maybe you need to check your spam folder. (I just resent a new email to you, so wait a moment and check again.
