### ISSUE TITLE
User doesn't exist

### ISSUE THREAD

**Issue by HongxuanLi-CB** [wuhan2020/volunteer-certificate#116]
![image](https://user-images.githubusercontent.com/63340444/78761085-b1a9f080-79b4-11ea-8953-faa988a9a88f.png)

I find the email  a month later, but it was invalid.
Could you please send another email to me?
My email is BlackSails_lhx@163.com.
Thank you!!!!!

**Comment by zhaofeng-shu33** [comment]
Please check your email box again.

**Comment by HongxuanLi-CB** [comment]
I have received the certificate. Thank you for your help!
