### ISSUE TITLE
[help wanted] 志愿者证书领取失败

### ISSUE THREAD

**Issue by heming6666** [wuhan2020/volunteer-certificate#117]
## 您的问题
收到志愿者证书领取邮件后，在页面上填写昵称信息提交后，在邮箱里没有收到证书邮件。

### 如果有的话，请附图
![image](https://user-images.githubusercontent.com/26642280/80664966-b866e780-8aca-11ea-98cd-263f9f6fe66a.png)

## 额外的信息
- 邮箱类别：Gmail
- 已检查垃圾邮件列表

**Comment by zhaofeng-shu33** [comment]
Please check your outlook email instead.

**Comment by heming6666** [comment]
Sorry for the late reply.

Actually this is a problem encountered by another volunteer. He used `gmail` to receive the 
volunteer certificate infomation before. So does this issue is caused by `gmail`?

My question is how can we change the email address to re-acquire the volunteer certificate?

Thank you @zhaofeng-shu33 very much!

**Comment by zhaofeng-shu33** [comment]
The certificate server is deployed within China so it may cause problems to reach gmail server.

**Comment by zhaofeng-shu33** [comment]
You can join `wuhan2020` private slack channel to provide details about which email is in use.

**Comment by heming6666** [comment]
We have received the volunteer certificate in the new email address. Thanks!
