### ISSUE TITLE
[功能拆分-后端] 3  后端项目批量给用户邮箱发邮件，定时任务

### ISSUE THREAD

**Issue by lovepoem** [wuhan2020/volunteer-certificate#12]
### 第1步. 后端项目批量给用户邮箱发邮件
   将为当前邮箱状态为0的邮箱生成token（可以定时任务扫描），并更新本行记录的token为新token
   每个邮件的关键内容为确认称呼的ur：
`https://community.wuhan2020.org.cn/zh-cn/certification/index.html?token=dsfasgdafgaggsdagdsg`

邮件发送完毕后，状态置为 1

**Comment by zhaofeng-shu33** [comment]
How to test this functionality?

**Comment by lovepoem** [comment]
1 ，集成测试，真的发邮件
2，mock发邮件的动作，其他单测补全，加一下测试覆盖率

**Comment by zhaofeng-shu33** [comment]
@youqingxiaozhua Do you know how to do test using mock in Python?

**Comment by zhaofeng-shu33** [comment]
I have `mocked` the SMTP library in the test of pr #34

**Comment by youqingxiaozhua** [comment]
> I have `mocked` the SMTP library in the test of pr #34

OK, tks, I will add a unit test of this feature.

**Comment by lovepoem** [comment]
Finished
