### ISSUE TITLE
邮箱发送次数限制方案解决

### ISSUE THREAD

**Issue by lovepoem** [wuhan2020/volunteer-certificate#72]
## 描述功能要求

邮箱发送次数限制方案解决

**Comment by lovepoem** [comment]
https://sa93g4.smartapps.cn/pages/question/question?qid=686782980019924812&_swebfr=1&hostname=baiduboxapp&from=groupmessage

**Comment by zhaofeng-shu33** [comment]
This is a big problem.

**Comment by zhaofeng-shu33** [comment]
@iLtc has mentioned the solution of [sendgrid](https://sendgrid.com).

**Comment by lovepoem** [comment]
> @iLtc has mentioned the solution of [sendgrid](https://sendgrid.com). It is said first 40000 emails are free.

https://github.com/sendgrid/sendgrid-python

**Comment by iLtc** [comment]
@lovepoem no need python library. SendGrid supports sending emails via SMTP.

**Comment by zhaofeng-shu33** [comment]
Great. We will consider using it if 163 mail really restricts 50 mails each day.

**Comment by zhaofeng-shu33** [comment]
@frank-zsy We have tested the maximum email is 200. Could you please investigate the solution of SendGrid?

**Comment by zhaofeng-shu33** [comment]
Currently we use aliyun company mails.

**Comment by lovepoem** [comment]
Good job
