### ISSUE TITLE
determine which api to use

### ISSUE THREAD

**Issue by zhaofeng-shu33** [wuhan2020/volunteer-certificate#9]
## 您的问题
Which one to use. `API/README.md` or `README.md`. We should determine this as soon as possible.

**Comment by lovepoem** [comment]
Use my new api 
https://github.com/wuhan2020/volunteer-certificate/commit/8c374e40e77e22e51f22f3aa9f9472585a02436a

**Comment by zhaofeng-shu33** [comment]
Well, I think we should reconsider this issue. I support using xin's API for the following reasons:
1. Easy to config: only 4 3rd party libs are used: Flask, Tinydb, yanmail and Pillow. And these libs do not have conflicts with each other
2. stateless: The backend is stateless. We use json data and do not need to deploy extra database. It is easy to transfer and deploy.
3. Less code: this API is coded in only two files and easier to maintain and improve.

**Comment by youqingxiaozhua** [comment]
> Well, I think we should reconsider this issue. I support using xin's API for the following reasons:
> 
> 1. Easy to config: only 4 3rd party libs are used: Flask, Tinydb, yanmail and Pillow. And these libs do not have conflicts with each other
> 2. stateless: The backend is stateless. We use json data and do not need to deploy extra database. It is easy to transfer and deploy.
> 3. Less code: this API is coded in only two files and easier to maintain and improve.

agree with the choice, but using json file as the dataset may need extra work to avoid concurrency conflicts.

**Comment by zhaofeng-shu33** [comment]
I do not think there will be many users who will use this API. Though we have 4000 registered users, many are not reachable. Of these reachable ones, many will not apply for the certificate.

I am not familiar with `tinydb` used in the project to read the json file as in-memory database. Maybe there will be concurrency problems if the endpoint is overloaded. I think we can improve this if this is really a problem in the future.

**Comment by zhaofeng-shu33** [comment]
Currently we also need to add cross-origin support in the backend app. Maybe we can use the `README.md` at root directory but start from the code of `API` directory to meet its requirements.

**Comment by lovepoem** [comment]
最后大家达成共识。在master当前分支上，逐步提交细小的pr
